CREATE DATABASE BankDb;
USE BankDb;

CREATE TABLE Banks (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Bank_Name NVARCHAR(30) NOT NULL
);

CREATE TABLE Cities(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	City_Name NVARCHAR(30) NOT NULL
);

CREATE TABLE Departments(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Department_code NVARCHAR(20) NOT NULL,
	City_Id INT NOT NULL,
	Bank_Id INT NOT NULL,
	CONSTRAINT FK_City_Id FOREIGN KEY(City_Id) REFERENCES Cities(Id),
	CONSTRAINT FK_Bank_Id FOREIGN KEY(Bank_Id) REFERENCES Banks(Id)
);

CREATE TABLE Clients(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Client_Name NVARCHAR(30) NOT NULL,
	Client_Surname NVARCHAR(30) NOT NULL,
	Birth_date DATE NOT NULL,
	Social_status NVARCHAR(20) NOT NULL,
	Department_Id INT NOT NULL
	CONSTRAINT FK_Department_Id FOREIGN KEY(Department_Id) REFERENCES Departments(Id)
);

CREATE TABLE Accounts(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Money_sum DECIMAL(18,2) NOT NULL,
	Client_Id INT NOT NULL,
	CONSTRAINT FK_Client_Id FOREIGN KEY(Client_Id) REFERENCES Clients(Id)
)

CREATE TABLE Bank_Cards(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Card_number NVARCHAR(30) NOT NULL,
	Date_from DATE NOT NULL,
	Date_to DATE NOT NULL,
	Money_sum DECIMAL(18,2) NOT NULL,
	Account_Id INT NOT NULL,
	CONSTRAINT FK_Account_Id FOREIGN KEY(Account_Id) REFERENCES Accounts(Id)
)